image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker compose down --remove-orphans

build image:
  stage: build
  script:
    - docker-compose build
  only:
    - main

build test:
  stage: test
  script:
    - docker-compose -f docker-compose-test.yaml up --build
  only:
    - main
    - develop



#pages:
#  image: alpine:latest
#  stage: deploy
#  before_script:
#  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
#  - eval $(ssh-agent -s)
#  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#  - mkdir -p ~/.ssh
#  - chmod 700 ~/.ssh
#  - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
#  - chmod 644 ~/.ssh/known_hosts
#  script:
#  - ssh $SSH_USER@$VM_IPADDRESS "hostname"
#  - scp -r . $SSH_USER@$VM_IPADDRESS:/root/fil_rouge
#  - ssh $SSH_USER@$VM_IPADDRESS "cd /root/fil_rouge && docker compose -f docker-compose-prod.yml up --build -d"
#  artifacts:
#    paths:
#    - public
#  only:
#  - main

