image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker compose down --remove-orphans

build image:
  stage: build
  script:
    - docker-compose build
  only:
    - main

build test:
  stage: test
  script:
    - docker-compose -f docker-compose-test.yaml up --build
  only:
    - main
    - develop



Production:
  image: alpine:latest
  stage: deploy
  before_script:
  - apk add --update sshpass openssh
  script:
    - sshpass -p $SSH_PASS ssh $SSH_USER@$VM_IPADDRESS -p 68 -o "StrictHostKeyChecking=no" "hostname"
    - sshpass -p $SSH_PASS scp -r . $SSH_USER@$VM_IPADDRESS -o "StrictHostKeyChecking=no" -P 68:/fil_rouge
    - sshpass -p $SSH_PASS ssh $SSH_USER@$VM_IPADDRESS -p 68 "cd /fil_rouge && docker compose -f docker-compose.yaml up --build -d"
  artifacts:
    paths:
    - public
  only:
  - main

