version: '3.8'

services:
    printplan-service: #API
        container_name: printplan-service
        build:
          dockerfile: Dockerfile
          context: printplan-api
          target: ${TARGET} #Dev ou Prod
        restart: on-failure #Ne sera redémarré qu'au déclenchement d'une erreur
        volumes:
            - ./printplan-api:/app
            - /app/bin
            - /app/obj
            - /app/api/bin
            - /app/api/obj
            - ./bin:/test-bin
            - ./obj:/test-obj
        depends_on:
            - printplan-bdd #Dépends du conteneur de base de données pour fonctionner
        networks:
            - net #Réseau permettant l'utilisation du reverse proxy de prod
            - intern #Réseau internet
        ports:
            - ${PORT_SERVICE}:80 #Exposition de l'api en local
        environment:
            TARGET: ${TARGET}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            # --------- Variables concernant le Reverse Proxy sur le serveur de prod
            VIRTUAL_PORT: 80
            VIRTUAL_HOST: uha.titouanfuchs.fr
            LETSENCRYPT_HOST: uha.titouanfuchs.fr

    printplan-bdd: #Base de données
        container_name: printplan-bdd
        image: postgres #Utilisation de PostgresSQL comme base de données
        restart: on-failure #Redémarrage uniquement au déclenchement d'une erreur
        volumes:
            - printplan-bdd:/var/lib/postgresql/data
        networks:
            - intern #La base de données ne sera pas accessible depuis l'exterieur
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            TZ: Europe/Paris

    printplan-pgadmin: #Espace de gestion de la base de données (accessible uniquement en local)
      container_name: printplan-pgadmin
      image: dpage/pgadmin4 #PGAdmin
      environment: #Identifiants pour accèder au PGAdmin
        PGADMIN_DEFAULT_EMAIL: admin@admin.fr
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
      ports:
        - ${PORT_PGADMIN}:80
      volumes:
        - pgadmin:/var/lib/pgadmin
      depends_on: #Dépends de la base de données
        - printplan-bdd 
      networks:
        - intern
volumes:
    pgadmin:
    printplan-bdd:
networks:
    net: # Réseau permettant l'utilisation du Reverse Prxy
      external: true
    intern: # Réseau local entre les différents conteneurs
        external: false
