version: '3.8'

services:
    printplan-service:
        container_name: printplan-service
        build:
          dockerfile: Dockerfile
          context: printplan-api
          target: ${TARGET}
        restart: on-failure
        volumes:
            - ./printplan-api:/app
            - /app/bin
            - /app/obj
        depends_on:
            - printplan-bdd
        networks:
            - intern
        ports:
            - ${PORT_SERVICE}:80
        environment:
            TARGET: ${TARGET}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    printplan-bdd:
        container_name: printplan-bdd
        image: postgres
        restart: always
        volumes:
            - printplan-bdd:/var/lib/postgresql/data
        networks:
            - intern
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            TZ: Europe/Paris

volumes:
    printplan-bdd:
networks:
    intern:
        external: false
