#////////////////////////////////////////////////////////

# Mise en place des bases du conteneur en utilisant DotNet SDK 7.0
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
#Dossier de travail
WORKDIR /app 

# On Copie l'intégralité du projet
COPY . /app 

# on restore toutes les dépendances du projet 
RUN dotnet restore

#////////////////////////////////////////////////////////

FROM base AS test-integration
WORKDIR /app

# On éxécute les tests d'intégration
RUN dotnet test "./api-integration-tests/api-integration-tests.csproj"
