#////////////////////////////////////////////////////////
# Mise en place des bases du conteneur en utilisant DotNet SDK 7.0
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /app # Dossier de travail

COPY . /app # On copie l'intégratlité du projet

RUN dotnet restore # on Restore les dépendances

#////////////////////////////////////////////////////////

FROM base AS test
WORKDIR /app

RUN dotnet test "./api-test/api-test.csproj" # on éxécute les tests unitaire
