#////////////////////////////////////////////////////////

# Mise en place des bases du conteneur en utilisant DotNet SDK 7.0
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /app #Dossier de travail

COPY . /app # On Copie l'intégralité du projet

RUN dotnet restore # on restore toutes les dépendances du projet 

#////////////////////////////////////////////////////////

FROM base AS test-integration
WORKDIR /app

# On éxécute les tests d'intégration
RUN dotnet test "./api-integration-tests/api-integration-tests.csproj"
