#////////////////////////////////////////////////////////
# Mise en place des bases du conteneur en utilisant DotNet SDK 7.0
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
# Dossier de travail
WORKDIR /app 

# On copie l'intégratlité du projet
COPY . /app 

RUN dotnet restore # on Restore les dépendances

#////////////////////////////////////////////////////////

FROM base AS test
WORKDIR /app

# on éxécute les tests unitaire
RUN dotnet test "./api-test/api-test.csproj"
