// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using printplan_api.Contexts;

#nullable disable

namespace printplan_api.Migrations
{
    [DbContext(typeof(PrintPlanContext))]
    [Migration("20231115110104_RemovedRandom")]
    partial class RemovedRandom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("printplan_api.Models.Core.FilamentSpool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Lenght")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FilamentSpools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            Lenght = 100,
                            Name = "Bobine_Courte",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            Lenght = 500,
                            Name = "Bobine_Moyenne",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black",
                            Lenght = 2000,
                            Name = "Bobine_Longue",
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("printplan_api.Models.Core.PrintModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("RequiredFilamentLenght")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PrintModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Petit model",
                            RequiredFilamentLenght = 5f
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moyen model",
                            RequiredFilamentLenght = 10f
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grand model",
                            RequiredFilamentLenght = 30f
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gargantua",
                            RequiredFilamentLenght = 1000f
                        });
                });

            modelBuilder.Entity("printplan_api.Models.Core.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PreheatingDuration")
                        .HasColumnType("real");

                    b.Property<float>("PrinterSpeed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Printers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Printer",
                            PreheatingDuration = 120f,
                            PrinterSpeed = 10f
                        });
                });

            modelBuilder.Entity("printplan_api.Models.Core.PrintingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentModelId");

                    b.ToTable("PrintingSlots");
                });

            modelBuilder.Entity("printplan_api.Models.Core.PrintingSlot", b =>
                {
                    b.HasOne("printplan_api.Models.Core.PrintModel", "CurrentModel")
                        .WithMany()
                        .HasForeignKey("CurrentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentModel");
                });
#pragma warning restore 612, 618
        }
    }
}
