// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using printplan_api.Contexts;

#nullable disable

namespace printplan_api.Migrations
{
    [DbContext(typeof(PrintPlanContext))]
    partial class PrintPlanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("printplan_api.Models.Core.FilamentSpool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Lenght")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FilamentSpools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            Lenght = 363,
                            Name = "Bobine_0",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            Lenght = 513,
                            Name = "Bobine_1",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black",
                            Lenght = 623,
                            Name = "Bobine_2",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 4,
                            Color = "Black",
                            Lenght = 515,
                            Name = "Bobine_3",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            Lenght = 608,
                            Name = "Bobine_4",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "Black",
                            Lenght = 498,
                            Name = "Bobine_5",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 7,
                            Color = "Black",
                            Lenght = 234,
                            Name = "Bobine_6",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 8,
                            Color = "Black",
                            Lenght = 995,
                            Name = "Bobine_7",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            Color = "Black",
                            Lenght = 975,
                            Name = "Bobine_8",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            Color = "Black",
                            Lenght = 115,
                            Name = "Bobine_9",
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("printplan_api.Models.Core.PrintModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("RequiredFilamentLenght")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PrintModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Petit model",
                            RequiredFilamentLenght = 5f
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moyen model",
                            RequiredFilamentLenght = 10f
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grand model",
                            RequiredFilamentLenght = 30f
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gargantua",
                            RequiredFilamentLenght = 1000f
                        });
                });

            modelBuilder.Entity("printplan_api.Models.Core.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PreheatingDuration")
                        .HasColumnType("real");

                    b.Property<float>("PrinterSpeed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Printers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Printer",
                            PreheatingDuration = 120f,
                            PrinterSpeed = 10f
                        });
                });

            modelBuilder.Entity("printplan_api.Models.Core.PrintingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentModelId");

                    b.ToTable("PrintingSlots");
                });

            modelBuilder.Entity("printplan_api.Models.Core.PrintingSlot", b =>
                {
                    b.HasOne("printplan_api.Models.Core.PrintModel", "CurrentModel")
                        .WithMany()
                        .HasForeignKey("CurrentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentModel");
                });
#pragma warning restore 612, 618
        }
    }
}
